### ISSUE TITLE
Feature Request | Exception/Blacklisted/Ignored Words

### ISSUE THREAD

**Issue by Owehttamy** [uku3lig/chathighlighter#4]
I wish there were an option to add a 'blacklist' alongside the 'whitelist' of highlighted strings.
For example, I'd love to make it so "<Owehttamy>" doesn't get highlighted because I added it as an exception to "Owehttamy." That way, whenever "Owehttamy" appears in chat, it's because someone's saying my name and not because I sent a message myself.
Another instance is when I want to see if someone says "end" in chat but not "enderman", "endermite", etc.

**Comment by uku3lig** [comment]
you can do that with regex fairly easily

**Comment by Owehttamy** [comment]
> you can do that with regex fairly easily
#5

**Comment by uku3lig** [comment]
Considering this fixed since #5 was closed
