### ISSUE TITLE
Issue with loading terrain when using ChatHighlighter mod 1.19.2

### ISSUE THREAD

**Issue by Emaryllis** [uku3lig/chathighlighter#7]
I just recently installed this mod to find out that it is incompatible. It does not give any start up errors. I have confirmed that this mod was causing my forever loading terrain which goes to a white screen. I removed only this mod to find that my loading terrain issue has been fixed and the minecraft client is able to render successfully.

**Comment by uku3lig** [comment]
weird, could you please attach a logfile?

**Comment by Emaryllis** [comment]
[2023-03-18-6.log](https://github.com/uku3lig/chathighlighter/files/11016963/2023-03-18-6.log)
[latest.log](https://github.com/uku3lig/chathighlighter/files/11016964/latest.log)

latest.log features the client working without the mod, the other log features it with the client not working as intended.

If it helps, the client chat was being logged, but on the display side the only thing I could see was "Loading Terrain" and no chat.

I also knew it was the problem because this error popped up when I read the log, so I knew where the problem was. Sure enough I removed it and it fixed it.
```
[23:50:47] [Render thread/WARN]: Could not access field text in class ChatHighlighterConfig
[23:50:47] [Render thread/WARN]: Could not access field color in class ChatHighlighterConfig
[23:50:47] [Render thread/WARN]: Could not access field alpha in class ChatHighlighterConfig
[23:50:47] [Render thread/WARN]: Could not access field usePattern in class ChatHighlighterConfig
[23:50:47] [Render thread/WARN]: Could not access field playSound in class ChatHighlighterConfig
[23:50:47] [Render thread/WARN]: Could not access field sound in class ChatHighlighterConfig
```
Don't worry about the other warnings, they shouldn't be anything game breaking, I have tested them and have been working as intended so far.

Also since its the same author, might as well paste another minor graphical issue: 
![image](https://user-images.githubusercontent.com/118420068/226324623-0c168517-d671-4e5f-abfa-fd3892564dae.png)

**Comment by uku3lig** [comment]
This is REALLY weird. Nothing apparent is found in the logfiles, so my best guess would be that there is some sort of conflict with another mod which causes this to arise? I have no clue

You could maybe try adding [fcwls](https://modrinth.com/mod/forcecloseworldloadingscreen) or [fastload](https://modrinth.com/mod/fastload) (i'd recommend the latter) to try and mitigate the issue.

As for the inaccessible fields issue, I am very confident about the fact that they aren't the source of the issue. This feature of ukulib never really worked and will be removed in the next release. As a last resort, I could try to make a patched version that disables this, but I highly doubt it would fix anything.

**Comment by uku3lig** [comment]
closing because stale
