### ISSUE TITLE
A problem with Chat Patches

### ISSUE THREAD

**Issue by iambeingtracked** [uku3lig/chathighlighter#9]
With [Chat Patches](https://modrinth.com/mod/chatpatches) installed it plays the mention sound every time you open the chat. Not sure if it's a fault of Chat Patches or chat highlighter but let it be there.

**Comment by iambeingtracked** [comment]
And it plays the sound more the more times you are mentioned in chat, which gets louder

**Comment by uku3lig** [comment]
thanks for reporting the issue! i have released 1.2.1 on modrinth which contains a fix

**Comment by iambeingtracked** [comment]
> thanks for reporting the issue! i have released 1.2.1 on modrinth which contains a fix

Nice, thank you homie. Will there be source code for it in the repo?

**Comment by uku3lig** [comment]
of course! i simply forgot to push my changes yesterday, see commit a2ec72df8e48e868410f71031392145b0447c970

**Comment by iambeingtracked** [comment]
oh, okay <3
